yarnpkg/website

en/docs/cli/config.md

Add docs for the config CLI command. See https://github.com/yarnpkg/website/issues/55

Document config CLI command

---

en/docs/package-json.md

Add package.json details

---

_posts/2016-10-11-introducing-yarn.md

When I first read it I thought I was a bit late to the party!

Fix post year

---

en/docs/yarn-lock.md

Fixed typo and added comma for pause.

Fixed typo in yarn-lock.md

---

en/docs/yarn-workflow.md

Fix typo in yarn-workflow.md

---

en/docs/version-control.md

Fix typo in version-control.md

---

_layouts/default.html

Right now all titles are "Yarn"...
this makes them unique, if possible.
Fixes #118

Unique titles for each page

---

en/docs/creating-a-package.md

Fix casing of Bitbucket in documentation

---

en/docs/cli/generate-lock-entry.md

Solve issue of missing navigation in docs/cli/generate-locker-entry

---

en/docs/_installations/linux.md

Add section about installing yarn on Arch Linux through AUR Helpers such as yaourt.

Add section about installing yarn on Arch Linux.

---

en/org/release-process.md

We'll definitely automate more of this, but I thought I'd at least document the current process.

Flesh out the release process page a bit more

---

en/docs/dependency-types.md

First pass at a description for this. Would love some feedback on it and open to changing it.

Add description for bundledDependencies

---

en/docs/package-json.md

This clarifies the role of scripts, gives (imo) a more concrete example,
and notes lifecycle scripts and when they're invoked.
This started as a simple typo fix and ended up a little more opinionated, and
I'm always happy to reword or change the direction of it.

Clarify the role of yarn scripts and note lifecycle scripts

---

_includes/navigation.html

UX more intuitive

---

en/docs/migrating-from-npm.md

This is counter-intuitive, but it works AFAIK.

Add NPM version of yarn upgrade

---

en/docs/_installations/windows.md

Chocolatey team approved the package: https://chocolatey.org/packages/yarn/0.15.0

Restore Chocolatey section now that it's approved 🎉🎉🎉

---

_includes/navigation.html

This makes keyboard navigation really annoying when navigation between pages

Remove autofocus

---

en/docs/_ci/circle.md

Fix typo in example circle.yml file

---

en/docs/cli/self-update.md

Possibility to update to certain version has been removed.
Merge after yarnpkg/yarn#676 has been released

Update docs for self-update

---

en/docs/cli/cache.md

[next release] Adding documentation for 'yarn cache dir'

---

_includes/footer.html
_sass/_footer.scss

The footer's margin was not really correct on the `xl` breakpoint. I added a negative margin to the `.footer` class to make the margin consistent.
Furthermore I sorted the breakpoints from `xs` up to `xl` as it is in other files as well.

Consistent footer margin

---

en/docs/_ci/codeship.md

Add installation instructions (via NPM) for use on [Codeship](https://codeship.com).

Add installation instructions for Codeship

---

en/docs/cli/add.md

The docs for add imply that there is no equivalent to npm I -g.

Refer to global command

---

_includes/navigation.html

This addresses issue #179 
Added a conditional statement to load the language selector in all pages except the blog page.

Add a conditional statement to load language selector

---

_config.yml

Fixes https://github.com/yarnpkg/yarn/issues/1283

Update version to 0.16.1 in _config

---

en/org/governance.md

Fix typo in governance.md: yarpkg => yarnpkg

---

en/docs/_ci/appveyor.md

https://www.appveyor.com/updates/2016/11/01/

Update AppVeyor page: Yarn is now preinstalled

---

en/docs/cli/global.md

Adding yarn upgrade to global docs(solves #234)

---

.gitignore
en/docs/cli/add.md
en/docs/migrating-from-npm.md

As per my merged PR: [https://github.com/yarnpkg/yarn/pull/1618](url)

Added short-flags for yarn add

---

.gitignore
en/docs/cli/upgrade.md

As per the merged PR: [https://github.com/yarnpkg/yarn/pull/1375](url)

Documented upgrade with engines-check

---

.gitmodules

Changed submodule

---

_config.yml

Bump latest version to 0.17.0

---

en/docs/_installations/tarball.md

Document how to use the changes per https://github.com/yarnpkg/yarn/pull/1928

Add docs for using the `--version` flag with the installation script

---

en/docs/_installations/tarball.md

- Note that it includes GPG signature verification.
- For people rightfully concerned about piping downloaded code to bash,
link to the source code of what's going to be run for inspection.

Add some notes about the safety of the tarball install method.

---

en/docs/cli/add.md

See https://github.com/yarnpkg/yarn/issues/1988

Clarify the symbol before commit-ish

---

_data/i18n/en.yml
_layouts/default.html
_layouts/page.html
_layouts/post.html
_posts/2016-12-01-lockfiles-for-all.md
_sass/_guides.scss

cc @cpojer @kittens @bestander @wycats @Daniel15

Blog post: Lockfiles for all

---

en/docs/cli/add.md
install.sh

@Daniel15  As per https://github.com/yarnpkg/yarn/issues/2061 (+ https://github.com/yarnpkg/yarn/pull/2071)

Fix install.sh

---

en/docs/package-json.md

This addresses part of the issues raised in #306.

Document the default value of the `start` script.

---

en/docs/cli/cache.md

We need to update the documentations for new features about cache-folder settings.
yarn version: 0.18.0
#303

update docs related to cache-folder settings for yarn version 0.18.0

---

_config.yml

cc @Daniel15 
I'll just merge, no more bug reports yet

Bump to 0.18.1

---

_sass/_navbar.scss

Fix language dropdown

---

search.html

Add title for /search.html

---

en/docs/_installations/alternatives.md

Fix spelling

---

_config.yml

0.19.1 marked as stable

---

_config.yml

Fixed regression since 0.19
* __fix errors thrown if symlink source does not exist (#2744)__

21.3 release

---

_data/i18n/en.yml
_includes/docsearch.html

Since the documentation is available in multiple langauges, the prompt should be too

feat(docsearch) mark placeholder for translation

---

js/src/install.js
js/src/lib/deeplink.js

fix(url) handle deep linked tabs before handling the current OS

---

lang/en/docs/_installations/windows.md

[Scoop](https://github.com/lukesampson/scoop) is a simple, developer-focused package manager for Windows.

Add Scoop to list of Install options for Windows

---

js/src/documentation.js
js/src/lib/Details/index.js
js/src/lib/Search/index.js
js/src/lib/config.js

these keys aren't confidential, since you can only search with it.
fixes #426

feat(config): put keys in a separate file

---

_data/i18n/en.yml
js/src/lib/Hit/index.js

Just like the other strings, the number can be in different locations based on teh language. The number will be displayed using Number.toLocaleString(), so it's localised itself

feat(search): mark count location in download string

---

js/src/package.js

Since the url isn't aware of which package detail we're on, we need to set the url to the correct package.
Doesn't work in `dev`, because `dev` doesn't have i18n
fixes #439 
PR deploy: https://deploy-preview-440--yarnpkg.netlify.com/zh-Hans/package/test

fix(detail): make changing languages work

---

_data/guides.yml
_data/i18n/en.yml
lang/en/docs/yarnrc.md

Docs for https://github.com/yarnpkg/yarn/pull/3035.

Add page for .yarnrc configuration options

---

lang/en/docs/_installations/mac.md

Brew now update by default before install command

Remove unnecessary command

---

lang/en/docs/creating-a-project.md

Grammar nit in docs

---

lang/en/docs/_ci/codeship.md

Update Codeship installation insructions

---

lang/en/docs/cli/install.md

- Add offline as a flag for yarn install docs

Add yarn install offline flag

---

lang/en/docs/yarnrc.md

Fix .yarnrc example

---

_config.yml

Not sure why this wasn't bumped yet.

Bump version to 0.23.3

---

scripts/set-version.sh

Add script to set version number in _config.yml

---

lang/en/docs/_ci/codeship.md

Codeship Basic has yarn pre-installed https://documentation.codeship.com/basic/builds-and-configuration/packages/

Update Codeship CI information

---

lang/en/docs/_installations/alternatives.md

Also made a small grammatical improvement.
Revision of #484

Correct warning about when npm is non-deterministic

---

_posts/2016-11-24-offline-mirror.md

It seems these two lines were missed when the post was updated last time. Here it is!

Add missing modification offline mirror post for offline mirror url change

---

_data/guides.yml
_data/i18n/en.yml
lang/en/docs/cli/upgrade-interactive.md
lang/en/docs/cli/upgrade.md

hope i haven't missed anything

added documentation for cli command upgrade-interactive

---

lang/en/docs/cli/install.md

Add documentation for `yarn install --check-files`.

Document yarn install --check-files

---

lang/en/docs/cli/install.md
lang/en/docs/cli/remove.md

Add --ignore-scripts to install command docs.
Add note about flags passed from remove command to install command. <-- Not sure if this should be promoted, if not then I am happy to remove it.

Update install and remove commands doc

---

_data/guides.yml
_data/i18n/en.yml
lang/en/docs/cli/create.md
lang/en/docs/cli/help.md
lang/en/docs/cli/import.md
lang/en/docs/cli/versions.md

Add missing docs for some commands

---

js/src/lib/Details/Usage.js

feat(detail): add a title to each dependency with its version

---

lang/en/docs/cli/run.md

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Add docs for yarn run v0.26.0

---

js/src/packages.js

Right now this is using the Algolia client, while it could use InstantSearch and be more explicit in what happens.
This saves about 100KB on the /packages url, since this file is now 1KB smaller and the Algolia response is quite a bit smaller too.

chore(featured): rebuild with InstantSearch

---

_posts/2017-06-16-supporting-more-registries.md

This also renames the file, I hope this doesn't break anything as this is not yet published?

Update date in Private Registry Support post

---

_posts/2017-06-19-adding-aliases-to-yarn.md
_posts/2017-06-19-adding-command-line-aliases-for-yarn.md

Close [yarnpkg/rfcs#65](https://github.com/yarnpkg/rfcs/pull/65).

New Blog Post: Adding Command Line Aliases for Yarn

---

lang/en/docs/cli/global.md

I learned something new in https://github.com/yarnpkg/yarn/pull/3458#issuecomment-310984999. :)  
I had looked for this information on this page many times before so this should some other people some time.

global: add docs for getting/setting symlink location

---

package.json
yarn.lock

chore(deps): update all deps 2017-06-30

---

js/src/lib/Details/index.js

I changed how Copyable works in #550 but forgot that it was also used in this 404-ish page. This fixed that!

fix(404): make Copyable back in line with change

---

lang/en/docs/cli/cache.md

Reference: https://github.com/yarnpkg/yarn/pull/3523

Update docs of `yarn cache clean` command

---

lang/en/docs/cli/install.md

CLI documents --frozen-lockfile. Also explain that it is very useful to be used with CI.

--frozen-lockfile added

---

lang/en/docs/cli/publish.md

Fix for https://github.com/yarnpkg/yarn/issues/3783

Document yarn publish --new-version

---

lang/en/docs/cli/upgrade-interactive.md
lang/en/docs/cli/upgrade.md

This is the documentation change for https://github.com/yarnpkg/yarn/pull/3847
These PRs should be merged at the same time.
See RFC https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-upgrade-command-consistency.md for details.

Upgrade version rework 3603

---

lang/en/docs/cli/global.md

To be merged with next release ^26.0.0

Rename ls to list in `yarn global` command

---

lang/en/docs/_installations/linux.md

Updating Node.js installation script

---

lang/en/docs/_installations/mac.md

docs(mac): update method to avoid installing node via brew

---

webpack.config.js

Slightly refactored `webpack` configuration

Webpack config

---

lang/en/docs/_installations/windows.md

To keep consistancy of the docs.

docs(windows): replace markdown code ```powershell by ```sh

---

js/src/lib/Details/FileBrowser.js

This was renamed at some point
Fixes #614

Change ?json to ?meta in Unpkg API call

---

webpack.config.js

Added [context](https://webpack.js.org/configuration/entry-context/#context) property for the sake of readability and maintainability

Change webpack configuration

---

lang/en/docs/cli/install.md

Document --non-interactive install flag

---

js/src/lib/Details/Aside.js
js/src/lib/Details/Markdown.js
js/src/lib/Details/index.js
js/src/lib/schema.js
js/src/lib/util.js

see https://github.com/algolia/npm-search/pull/53

fix(github): use git repo head instead of gitHead

---

_data/guides.yml
_data/i18n/en.yml
lang/en/docs/selective-version-resolutions.md

Update: Add docs for selective version resolutions

---

lang/en/docs/selective-version-resolutions.md

Update selective-version-resolutions.md fixes issue#639

---

lang/en/docs/_installations/mac.md

maybe it will helpful if other OS upgrade methods were listed too

Added how to upgrade Yarn for Mac

---

_posts/2017-07-26-introducing-workspaces.md

- the the -> the
- chalk/` -> chalk/
- an different -> a different
- add missing point

Fix minor grammar issues

---

lang/en/docs/cli/init.md

It's related to https://github.com/yarnpkg/yarn/pull/4165 and https://github.com/yarnpkg/yarn/pull/4377

Update introduce for private flag of git init command

---

lang/en/docs/cli/install.md

Dear community,
Please review my code.
Related issue : https://github.com/yarnpkg/yarn/issues/788
Best,
Alpha

UPT: Document of yarn install flag

---

js/src/lib/Search/index.js

fixes #662
What do you think @scarlac?

feat(search): focus on homepage

---

lang/en/docs/cli/info.md

Mainly for SEO reasons so people can find it quicker!

Add an example of checking available versions

---

lang/en/docs/cli/run.md

fixes #666 
fixes #656 
fixes #306

docs(run): document advanced usage

---

lang/en/docs/cli/cache.md
lang/en/docs/cli/list.md
lang/en/docs/cli/upgrade.md

Adds documentation about the new pattern flag on a few commands.
@arcanis I guess this can't really be merged until that feature is released though.

Pattern docs

---

_redirects

Are there other commands that changed name @bestander?

chore(redirects): redirect clean -> autoclean

---

_posts/2017-06-19-adding-command-line-aliases-for-yarn.md

https://github.com/yarnpkg/yarn/pull/3898
Also tighten intro to Powershell (current Windows versions run powershell as default shell from Win+x, don't include cmd anymore)

Add powershell ls alias per @bestander request

---

_includes/navigation.html
_sass/_navbar.scss

Mobile menu fixes

---

lang/en/docs/package-json.md

docs(package.json): add docs for the `resolutions` block

---

_data/languages.yml

AFAICT this should be all the changes needed, since it's 97% translated I think we should enable it. 
closes #701

feat(i18n): enable japanese

---

_layouts/pages/detail.html
_sass/_heros.scss

fixes #704 
1 rem seemed a bit little, but 2rem works nice I think
cc @yfdyh000

style(hero): smaller margins

---

_data/i18n/en.yml
js/src/lib/Details/Aside.js
js/src/lib/Details/Cdn.js
js/src/lib/Details/index.js
lang/en/package.html

Add CDNs header under Use it (#723)

---

js/src/lib/Details/Cdn.js

Randomizes the order of the CDNs in the CDN list on a package page. See discussion in #723

Randomize order of CDNs

---

_data/guides.yml
_data/i18n/en.yml
lang/en/docs/cli/dedupe.md
lang/en/docs/cli/lockfile.md
lang/en/docs/cli/prune.md

Docs: Add dedupe, lockfile and prune CLI commands.

---

lang/en/docs/yarn-lock.md

Current explanation in the blog is more accurate.

Add link to blog for more detail about lock files

---

_includes/i18n-as-script.html

Fix for: https://github.com/yarnpkg/website/pull/740#issuecomment-351954905

Deeper copy defaults

---

lang/en/docs/envvars.md
lang/en/docs/yarnrc.md

Fixed yarnrc syntax highlight

---

_sass/_readmore.scss

I was also wondering if is a good idea to use `cursor: pointer` in `<details>` (like GitHub does in its markdown)

Use 'cursor: pointer' on readMore button

---

_data/languages.yml

Ukrainian Translation is 92% complete. I constantly update new translations on crowdin. It would be good to enable it on production site.

Enable Ukrainian Translation on site

---

lang/en/docs/cli/cache.md

Related: https://github.com/yarnpkg/yarn/issues/5273

Update documentation for cache clean with multiple parameters

---

_data/languages.yml

🇮🇩🇹🇷🇪🇸 are all +90% in the translations!

enable new languages

---

lang/en/docs/cli/install.md

ignore-optional

---

lang/en/docs/package-json.md

Explain the semver exception introduced in https://github.com/yarnpkg/yarn/pull/5352

Document semver exception

---

install.sh

Update install.sh to check for proper GPG subkey

---

js/src/lib/Details/Links.js

remove new tab from package detail links

---

_data/guides.yml
_data/i18n/en.yml
lang/en/docs/cli/workspace.md

hello there 👋,
while working with `yarn workspace`, I didn't found any reference in the Yarn website,
i hope with this pr, we can open the conversation about it,
seems we already have related issues:
https://github.com/yarnpkg/website/issues/573
https://github.com/yarnpkg/website/issues/563
the wording is far from perfect, any guidance would be appreciated,
thanks 🤗

[feat] add cli `workspace` command page and basic example

---

lang/en/docs/workspaces.md

I didn't find this option when using search in doc. I used github issues, find the option... then found a comment leading to this blog post.

Docs: add nohoist option on Workspaces page.

---

lang/en/org/contributing.md

- Gave header an anchor
- Added some more information around the testing process to make it clearer to consumers

docs: improved testing changes locally

---

lang/en/docs/cli/version.md

This adds documentation for yarnpkg/yarn#5640 and yarnpkg/yarn#5670.

Adding documentation for semver versioning flags and commit hook control

---

_data/guides.yml
_data/i18n/en.yml
lang/en/docs/cli/workspaces.md

docs(workspaces): add initial cli docs for workspaces.

---

lang/en/docs/cli/add.md

Add initial documentation for how to add a dependency and reference it with an alias.

add instructions for aliasing a dependency

---

lang/en/docs/_installations/windows.md

windows.md typo fix: period instead of comma

---

lang/en/docs/migrating-from-npm.md

instead of `yarn install --force`.

yarn add --force for npm rebuild

---

lang/en/docs/workspaces.md

Changing "less conflicts" to "fewer conflicts"

Small grammatical change to workspaces docs

---

_posts/2018-05-18-focused-workspaces.md
lang/en/docs/cli/install.md
lang/en/docs/workspaces.md

Focused workspaces documention and blog post

---

lang/en/docs/cli/import.md

Adjusted documentation to reflect https://github.com/yarnpkg/yarn/pull/5745

docs(import): adjust for package-lock.json import

---

lang/en/docs/cli/add.md

docs(add): Add documentation for ignore-workspace-root-check

---

lang/en/docs/cli/install.md

...and also add a period to the end of a sentence.

fix a typo in install.md

---

_posts/2018-02-15-nohoist.md

Confirmed fix by editing the URL via the dev tools on the live site.

Fix broken image in 2018-02-15-nohoist.md

---

lang/en/docs/creating-a-package.md

- update example URLS to HTTPS to encourage best practises
- update choosealicense.com to HTTPS

https all the things

---

lang/en/docs/migrating-from-npm.md

yarn add is equivalent to npm install --save

Update CLI commands comparison

---

_data/guides.yml
_data/i18n/en.yml
lang/en/docs/cli/add.md
lang/en/docs/cli/audit.md
lang/en/docs/cli/install.md

fixes #877 
Add some initial docs for the `yarn audit` command

Add docs for Audit command

---

lang/en/docs/cli/version.md

Adding section about lifecycle methods and environment variables available in these

Add lifecycle methods and environment variables

---

_layouts/pages/install-ci.html

now tab will deactivate if other tab selected and can selected again.

Fix tabs behaviours on installCI page

---

lang/en/docs/_installations/debian.md

Add missing `sudo`  in install command to avoid permission error.

Update debian.md, Add missing `sudo`

---

lang/en/docs/workspaces.md

I found this missing each time I tell someone to read the doc. 
Hope it will helps others :)

Add more details about workspaces implementation

---

lang/en/docs/cli/cache.md

docs: add cache note

---

_data/i18n/en.yml
_layouts/pages/install-ci.html
lang/en/docs/_ci/gitlab.md

Does pretty much what it says in the title.

Adds GitLab to the Continuous Integration page

---

lang/en/docs/pnp/getting-started.md

It sounds like `with` should be `without` so this fixes that. Unless I've understood the context wrong.

Fix Spelling Error

---

_posts/2018-02-15-nohoist.md

The text is hard to read in the rendered format in the website.

Fix style issue in nohoist blog post

---

_posts/2016-10-11-introducing-yarn.md

It actually took me a while to figure out just which companies were meant; lets save others the time.

First post: Add links for the participating companies

---

_posts/2017-07-26-introducing-workspaces.md

Fixed typo

---

lang/en/docs/cli/workspace.md

I couldn't find documentation for this flag anywhere.

remove --save flag from workspace command docs

---

_posts/2019-07-12-recommended-security-update.md

Adds a blog post to explain the latest security incident

---

lang/en/docs/pnp.md

Resolves https://github.com/yarnpkg/yarn/issues/6637

docs(pnp): Add disambiguation from the `pnpm` package manager

---

lang/en/docs/package-json.md
lang/en/docs/selective-version-resolutions.md

Explicitly mention ranges in resolutions doc

---

_posts/2016-12-01-lockfiles-for-all.md

This is a picky grammar change. Feel free to ignore and close :stuck_out_tongue: 
https://www.quickanddirtytips.com/education/grammar/ie-versus-eg

docs Change i.e. to e.g.

---

lang/en/docs/yarn-lock.md

- add comma to otherwise confusing sentence

fix typo in lang/en/docs/yarn-lock.md

---

lang/en/docs/migrating-from-npm.md

install to add

---

lang/en/docs/getting-started.md

I spend much time, because I've searching usage of this package manager.
To be right, I want to know for which lang it uses. It's really good info, you can share code and so on, but I can't share my python/php/golang code through (Yea I can, but it will be very stupid)
This main/getting started has no any word about js. 
I found info about Yarn only from wiki about Npm

Updated the main page, as there is no information on the connection between the package manager and the language / technology for which it is used

---

lang/en/docs/_installations/unix_path_setup.md

Resolves https://github.com/yarnpkg/website/issues/1027

Update fish shell path instructions

---

lang/en/docs/_installations/debian.md

The anchor changed on the nodejs site

Update debian nodesource link

---

lang/en/docs/cli/audit.md

Basic doc for  yarn audit --groups command introduced byhttps://github.com/yarnpkg/yarn/pull/6724

Document yarn audit --groups

---

lang/en/docs/cli/self-update.md

Remove extra - in self-update.md
