yarnpkg/website

- en/docs/dependency-versions.md
Correct the versions used in the [comparator-section](https://yarnpkg.com/en/docs/dependency-versions#toc-comparators).
> Fix version typos

- en/docs/cli/cache.md
`yarn cache clear` does not work, but `yarn cache clean` does. `clear` gives the following error:
```
% yarn cache clear
yarn cache v0.15.1
error Invalid subcommand. Try "ls, clean"
info Visit http://yarnpkg.com/en/docs/cli/cache for documentation about this command.
```
> Fix cache clean docs

- en/docs/cli/global.md
So, either the link is wrong, or the name is wrong. I am pretty sure that this was meant to be for `yarn ls` and not `yarn init`, but let me know if that's incorrect!
> Fix doc link for yarn ls

- en/docs/creating-a-package.md
- en/docs/package-json.md
Corrected all mentions of _gitlub_ in the docs to _github_. I assume this was a mistake (not a mix of Github and Gitlab!) as there are many references to Github which are spelt correctly.
> Corrected 'gitlub' in docs to 'github'

- en/docs/usage.md
Hi guys,
The typo is there on this https://yarnpkg.com/en/docs/usage page. 
Thanks!
> Fixed a minor grammatical typo.

- _includes/navigation.html
As mentioned in Bootstrap's docs:
> If the `<a>` elements are used to act as buttons – triggering in-page functionality, rather than navigating to another document or section within the current page – they should also be given an appropriate `role="button"`.
> Specify role of <a> dropdown

- en/docs/cli/add.md
- en/docs/dependency-types.md
- en/docs/dependency-versions.md
- en/docs/yarn-lock.md
incomplete sets of examples should be marked 'e.g.' not 'i.e.'
> i.e. → e.g.

- en/org/contributing.md
This link is also in the footer template, but it doesn't hurt to make it easier to find by including the link where it is referenced inline on the contributing page.
> Add link to BSD license

- _data/guides.yml
- _data/i18n/en.yml
- en/docs/cli/test.md
The documentation for the `test` command was missing so I decided to add it in with the first commit.
~~In the second commit, I added more information about system-wide commands not being executable by Yarn. Since it's possibly a breaking change for people coming from npm, I felt it should be proactively addressed in the docs.~~
~~The third commit just adds a missing `p.lead` tag to `run`.~~
I tried to lift the wording and formatting from other doc entries.
> docs/cli: Added test command docs.

- en/org/contributing.md
The current contributing page was using npm rather than yarn in the instructions for how to run build/watch/test/lint commands.
Probably would make more sense to use yarn, and dogfood our own 'yarn run' command :)
> Modifying contributing page to use yarn rather than npm

- en/docs/_installations/linux.md
As yarn is now available in [Solus](https://solus-project.com) (both stable and unstable repos), I've added instructions on how our users can obtain yarn.
> Added the yarn installation instructions for the Solus operating system

- _sass/_features.scss
- _sass/_featurettes.scss
- _sass/_footer.scss
- _sass/_heros.scss
I've made some small changes to the type, just to clean it up a little.
Before:
After:
I should have covered all the smaller screen sizes as well.
Feel free to accept, or if you'd prefer to keep tight control of the design I understand too… feel welcome to close.
> Type improvements

- en/docs/_installations/alternatives.md
- en/docs/_installations/linux.md
- en/docs/_installations/mac.md
- en/docs/_installations/unix_path_setup.md
- en/docs/_installations/windows.md
- en/docs/_installations/windows_path_setup.md
This adds documentation on setting up the path environment variable to provide global access to yarn's bin folder.
> Add path setup to installation documentation

- en/docs/package-json.md
This documents the ability to add `"flat": true` as an entry in `package.json`
to enforce the semantics of `yarn install --flat` on every installation, as
implemented in [yarnpkg/yarn#299](https://github.com/yarnpkg/yarn/pull/299). This also notes the drawbacks involved in doing so
(forcing flatness upon consumers of the package).
**This is not ready to merge yet because:**
The only outstanding issue is the link generated using `{{url_base}}` doesn't
include the language, despite it working on other pages. Let me know how to fix
that up and I'll take care of it :)
Also open to rewording things.
> Document `package.json` entry `"flat": true`

- en/docs/_installations/mac.md
This might be obvious for long time OS X users, but my first attempt to install `yarn` ended up with:
```sh
$ brew install yarn
Error: No available formula with the name "yarn" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
==> You haven't updated Homebrew in a while.
A formula for yarn might have been added recently.
Run `brew update` to get the latest Homebrew updates!
```
Why we should add this:
1. `brew update` before install will save us, newbies, from facing this error
1. I think it's a good practice, docs for linux that involve installation of new stuff usually start with with `sudo apt-get update` or `sudo yum update` and not with the actual `sudo apt-get install x-y` step.
> run brew update before install

- _includes/footer.html
`/org/translating` is not found.
> Fix broken link

- en/docs/_installations/mac.md
Homebrew downloads the tarball and is basically better in every way. We should no longer suggest the installer or manually extracting the tarball for Mac OS users (it's fine to be in the "alternatives" tab just like for the other operating systems). Also, it's a better first impression if people go to the installation page and **don't** see a `curl | sh` 😛
> Remove tarball steps from Mac OS page

- en/org/release-process.md
Updates the instructions now that a lot more stuff is automated: CircleCI is building all the Linux packages and AppVeyor is building the Windows installer.
I kept the existing manual instructions just in case something breaks
cc @bestander
> Update release process instructions

- _data/guides.yml
- _data/i18n/en.yml
- en/docs/_ci/appveyor.md
- en/docs/_ci/circle.md
- en/docs/_ci/travis.md
- en/docs/install_ci.html
Documents how to configure Yarn in AppVeyor, CircleCI, and Travis CI, including caching of the Yarn cache across builds.
The tabs are ordered alphabetically, so AppVeyor > CircleCI > Travis
> Document how to use Yarn in continuous integration systems

- en/docs/cli/team.md
Added docs for yarn team. This section is currently missing documentation on the website.
* [/src/cli/commands/team.js](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/team.js)
> add yarn team docs

- en/docs/cli/init.md
This fixes #144. Also, this probably shouldn't land until a new release of Yarn is cut which has this feature.
> [next release] Add documentation for init --yes command

- en/docs/dependency-versions.md
Changed "it's" to "its" in the context of "When you want to specify a dependency you specify ITS name".
> Fixed incorrect "it's"

- en/docs/install-ci.html
- en/docs/install.html
- js/deeplink.js
A response to issue #201 
The scripts detects the presence of a hash in the URL and a '.tabs' element on the DOM.
It activates the tabs with the same ID as the hash.
It removes the hash from the URL if there are no matching tabs.
It adds the hash of a tab on the URL bar when a tab is clicked.
> Add tab deep linking

- en/org/release-process.md
Currently there's a TODO task showing on the page :
TODO: Instructions for updating Chocolatey should go here - Currrently Daniel does that manually
I'm assuming this is not meant to be shown on the site, only in the source code. 
I changed the TODO into a reference style link. It's a hack but I believe it's the only way in Markdown to keep comments out of the HTML output as discussed [here](http://stackoverflow.com/questions/4823468/comments-in-markdown)
`[TODO]: <> (Instructions for updating Chocolatey should go here - Currrently Daniel does that manually)
`
This also triggers the Internal Developer Info panel which only shows in development environments.
> Remove TODO from output html and replace it with a reference style blank link

- en/docs/migrating-from-npm.md
This correlation was mentioned as being correct in #192 and https://github.com/yarnpkg/yarn/issues/1163.
> Fix #192 Document `npm rebuild equivalent` as `yarn install --force`

- _sass/_search.scss
currently this happened on <1085px, but actually the nav gets slimmer from 1200px
suggested as a problem to fix by @thejameskyle in #208
> break search bar into a smaller width on focus

- _data/guides.yml
- _data/i18n/en.yml
- _includes/additional-reading.html
- en/docs/cli/add.md
- en/docs/cli/tag.md
- en/docs/cli/upgrade.md
- en/docs/dependency-versions.md
- en/docs/managing-dependencies.md
Not sure if this is overkill or what, several of the onboarding docs mention this usage of `yarn upgrade` but it wasn't fleshed out in the docs at all, so i decided to add it and experimented with the behavior of the command to give folks a good idea of how it behaves in various cases.
I didn't immediately come across a documentation style guide or anything, but tried to keep things within the house style.
> documentation update for `yarn upgrade` command

- en/docs/cli/version.md
As well as other config values that affect `yarn version --new-version`.
Supercedes PR#222
> Document `yarn version --new-version --no-git-tag-version`

- en/docs/yarn-lock.md
Previously was `package-4^@4.0.0` (transposed caret and asperand), changed to `package-4@^4.0.0`
> Correct demonstrated version range for "package-4"

- en/docs/cli/add.md
The docs were explicitly refering to acting on a single package, which was inaccurate.
The ellipse in `<package...>` is there to imply that multiple packages
are supported, but the notation is universally recognized. Updating
the text improves the clarity that the `add` sub-commnand can work on
multiple dependencies at once.
> Update docs for `add` to clarify that it can work with multiple packages.

- en/docs/cli/index.md
- en/docs/cli/install.md
Mentions of this feature were added in two places:
1. The CLI overview for page where one might look to see what the default action is.
2. The `install` page, where someone might be interested to find the
shortcut.
> Document that `install` is the default `yarn` command.

- en/docs/_ci/circle.md
- en/docs/_ci/travis.md
- en/docs/_installations/linux.md
We've seen `pgp.mit.edu` fail a few times, and other keyservers have issues too (eg. see https://github.com/docker/docker/issues/20022). I've changed our instructions to load the GPG public key from a URL we host, rather than a keyserver. This will hopefully make installations less flaky (they won't fail when the keyserver has issues)
HTTPS doesn't work in all environments, so I'm just using regular HTTP:
> gpgkeys: protocol 'https' not supported
> gpg: no handler for keyserver scheme 'https'
> gpg: WARNING: unable to fetch URI https://dl.yarnpkg.com/debian/pubkey.gpg: keyserver error
> Load GPG key from URL rather than keyserver

- en/docs/cli/run.md
This commit contains two additions:
1. additional arguments for `yarn run`
2. `[script]` can also be any executable inside `node_modules/.bin/`
> docs for yarn run <args>

- en/docs/creating-a-package.md
The yarn website contains a mention of `npm init` which should probably be changed to `yarn init`, this PR fixes that.
> Remove reference to npm

- en/docs/cli/ls.md
Documentation for added functionality at [#1463](https://github.com/yarnpkg/yarn/pull/1463)
> Add documentation for ls and ls --depth command

- _data/i18n/en.yml
- en/docs/_installations/nightly.md
- en/docs/install.html
References https://github.com/yarnpkg/yarn/issues/1474
> Document nightly builds on download page

- _data/guides.yml
- _data/i18n/en.yml
- _data/nightly_types.yml
- en/docs/_installations/nightly.md
- en/docs/install.html
- en/docs/nightly.html
- js/nightly.js
Moves the page at https://nightly.yarnpkg.com/ onto the main site. The list of available builds is loaded via an AJAX request from the nightly build server.
Once this lands, I'll make https://nightly.yarnpkg.com/ redirect to it and kill that old page. It was mainly for prototyping some ideas 😄 
cc @thejameskyle 
Closes #259
> Move nightly builds page to site

- _config.yml
There's been quite a few breaking bugs reported with 0.17.0, so I feel like we either need to roll back to 0.16.1 or roll forward and release a patched version (eg. 0.17.1). I'll leave this up to you to decide what to do - Feel free to merge this PR if you want to roll back, or just close this PR if you roll forward.
Currently the installation script is breaking and it uses this version number to determine the version to install.
@yarnpkg/core
> Revert version to 0.16.1

- en/docs/_ci/circle.md
- en/docs/_ci/deb-specific-version.md
- en/docs/_ci/travis.md
Now that our Debian repo can contain multiple version of Yarn (implemented in https://github.com/yarnpkg/yarn/issues/1839), we should advocate locking the version of Yarn used in CI environments. The main reason is so that people's builds don't suddenly break because they're always installing the latest version of Yarn (which could have breaking changes for their environment) 😛
> Add information about installing specific version of Yarn on Travis and Circle

- en/docs/_installations/linux.md
There's no need to run curl as root if it's writing the contents to standard output. Verified that the new command works just as well on my Debian system.
> Remove redundant sudo from Debian install instructions

- en/docs/_installations/unix_path_setup.md
When installing with Homebrew or other tools, yarn doesn't always use `~/.yarn/bin`. Instead direct users to use `yarn global bin` to refer to the correct path.
> Refer to `yarn global bin` in path setup

- en/docs/_ci/circle.md
Without `override`, CircleCI will run `npm install` instead of `yarn install`
> Fix CircleCI instruction

- en/docs/_ci/travis.md
Travis CI has announced Yarn support on 2016-11-21. https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
This update describes the current support status of Travis CI on that date.
> Update Travis CI integration

- _config.yml
- _redirects
- install.sh
This makes more sense to live on the site or in the releases repo, as it's not a part of Yarn itself. This is similar to what other projects with installation scripts do - The installation script lives on the site.
References https://github.com/yarnpkg/yarn/issues/2058
> Move installation script to site rather than living in the Yarn repo

- en/docs/cli/init.md
The list of variables was found by reviewing the source code for the `init` command.
> init: document config variables that can influence `yarn init`.

- en/docs/_installations/tarball.md
The package is not named `yarn-*` except if you pass `-o` to `wget`, which is not the case.
> [Docs] Fixed tar command

- install.sh
I manually tested both the success and failure cases. 
This patch uses the `--perl-regexp` option to `grep`. I did not attempt a comprehensive check of which OS versions support this flag. It is supported with the GNU grep that ships with Ubuntu 16.04.
> Fix #294: Validate  value provided to --version before using it.

- en/docs/cli/index.md
Adds a note in `cli/index.md` describing usage of the `--mutex` flag in both file and network modes.
Fixes #261
> Add documentation for --mutex

- install.sh
This fixes `yarn install --version` on with BSD grep, used by macOS.
This pull request is an alternative to PR #298, which did not work on Ubuntu Linux.
> Portability: Use more common "Extended Regex" instead of "Perl Regex"

- en/docs/_installations/alternatives.md
I tried to be as neutral as possible while writing this, let me know if it doesn't make sense.
> Add note about why installing via npm is not recommended

- install.sh
[BusyBox](https://busybox.net/BusyBox.html)'s mktemp requires that:
> TEMPLATE (-t parameter) must end with XXXXXX (e.g. [/dir/]nameXXXXXX).
> Fixes yarnpkg/yarn#2122 - mktemp invalid argument

- Makefile
- README.md
- _config.yml
Hey guys,
I've recently started playing with Yarn's website and I was surprised by Jekyll's build time and the overall poor dev experience while updating a page.
Here are 2 small things making the build time after each save going down from ~10 to <2 sec:
- ignore .sass-cache/ and _saas/bootstrap from the watch list
- enable Jerkyl's incremental build (regenerate only what has changed)
Before:
```
Server address: http://127.0.0.1:4000/
Server running... press ctrl-c to stop.
Regenerating: 1 file(s) changed at 2016-12-18 11:34:13 ...done in 9.677989 seconds.
```
After:
```
Server address: http://127.0.0.1:4000/
Server running... press ctrl-c to stop.
Regenerating: 1 file(s) changed at 2016-12-18 11:35:16 ...done in 1.73356 seconds.
```
Hope that helps :)
> Dev: `jekyll serve` perf improvement

- en/docs/_ci/appveyor.md
Forward slash gives me `Cache 'C:\Users\appveyor\AppData\Local/Yarn' - Calculating checksum...Error calculating CRC32 for C:\Users\appveyor\AppData\Local/Yarn\cache\npm-abab-1.0.3\.yarn-metadata.json: The filename, directory name, or volume label syntax is incorrect`
> Use windows path separator in appveyor cache

- _includes/docsearch.html
- _includes/footer.html
- en/docs/index.html
Previously we were instantiating docsearch on every page resulting in
console errors.
> docs(search): only init docsearch when relevant

- en/docs/cli/global.md
--prefix option for yarn global command (https://github.com/yarnpkg/yarn/pull/1654) was not mentioned in documentation for yarn global command. Also this option is not applicable for yarn add command. This PR will help users to find out common usage to install a common package globally to a specific directory.
> Mention prefix option for yarn global add command

- js/search.js
Hi :) We noticed a change in the URL pattern on NPM. Right now it's mostly invisible since they have a redirect, but it doesn't work with all the packages (`search` for example). Fixing it to make it more future proof :)
> fix(search): url pattern changed on NPM

- en/docs/_ci/circle.md
- en/docs/_ci/travis.md
yarn is [now cached in ~/.cache/yarn](https://github.com/yarnpkg/yarn/blob/a1192e596b85acb2f63daa1cbf30e662c2125310/src/constants.js#L41), not ~/.yarn-cache.
> ci: Update yarn cache directory

- en/docs/cli/ls.md
The `ls` command was renamed to `list` in [yarn@0.18.0](https://github.com/yarnpkg/yarn/releases/tag/v0.18.0)
> 📝 ls → list

- en/org/release-process.md
Currently all pushes to `0.xx-stable` branches with tags are considered `stable` by default.
I changed the doc and planning to change release scripts in Yarn repo so that all pushes are considered as `RC` and a maintainer needs to manually declare an `RC` release as stable
> Updated release doc to account for stable tag

- _layouts/default.html
it wasn't showing up before, because the layout file didn't have a case for a non-blogpost that had a title, so now there's another condition for that.
see #331 where a page.title was added to that page
> add a page title to the /search page

- _config.yml
- _data/i18n/en.yml
- _includes/navigation.html
- _redirects
- install.sh
- latest-rc-version
- Add `/latest-rc-version` endpoint to return version number
- Add `--rc` flag to installation script
- Add redirects for RC version (eg. `/latest-rc.tar.gz`)
- Show RC version number on site
I'll make a script that automatically bumps this version number on new releases, based on whether the GitHub release is marked as stable or not.
References https://github.com/yarnpkg/yarn/issues/2161
cc @bestander
> Add RC to website

- en/docs/cli/self-update.md
The self-update feature was removed pending a more robust
implementation. At present, it's not clear from the CLI or otherwise
that self-update was removed. This gives an indication in the
documentation that at least the user is not using it incorrectly.
> #339 Add note explaining no self-update in 0.18.1

- install.sh
Currently, when running the installer twice from the same dir, the following error occurs:
```
Installing Yarn!
/var/lib/buildkite-agent/.yarn/bin/yarn
> Yarn is already at the 0.19.1 version.
> Downloading tarball...
[1/2]: https://yarnpkg.com/latest.tar.gz --> /tmp/yarn.tar.gz.iSzFfDLgpA
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    92  100    92    0     0    667      0 --:--:-- --:--:-- --:--:--   671
0     0    0   595    0     0   3227      0 --:--:-- --:--:-- --:--:--  3227
100 3416k  100 3416k    0     0  9290k      0 --:--:-- --:--:-- --:--:-- 75.4M
[2/2]: https://yarnpkg.com/latest.tar.gz.asc --> /tmp/yarn.tar.gz.iSzFfDLgpA.asc
100    96  100    96    0     0   1561      0 --:--:-- --:--:-- …
```
> fix: do not fail if .yarn dir exists

- en/docs/usage.md
Given that the command is called `upgrade`, the title should echo this.
> Docs: Consistent use of Upgrading / upgrade

- _sass/_search.scss
Description now shows the query matches in an highlighted fashion like
others fields are.
**Before**
**After**
> feat(search): Also highlight description

- _sass/_search.scss
- search.html
Before this commit, the pagination on search results was not
centered, this looked weird.
Also adjusted margins so that pagination does not insert itself
too close to last result.
> docs(search): horizontally center pagination and adjust margins

- _includes/navigation.html
I saw this, and was like "Awesome 🌟"
So I went to the site and tried to click on this:
and it didn't work, so I figured I could contribute back 💯 
Which will take you to https://github.com/yarnpkg/yarn/releases/tag/v0.19.1
> Adds a link to the corresponding GitHub release page in the nav

- lang/en/docs/_ci/travis.md
Reference: [Travis's node_js doc](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Travis-CI-supports-yarn).
> ci/travis: Use yarn's cache directive in examples

- install.sh
This causes the install script to fail unless the current directory is `$HOME`. This is not the case if, like me, you are running the install script as part of building a Docker image for a continuous build.
Note that all other references to `.yarn` are **already** `$HOME/.yarn`
> replace ./.yarn -> $HOME/.yarn

- js/src/documentation.js
The documentation has been written in a few languages now, but was only crawled in English. 
Now the setup has been put in place for documentation in multiple languages (see https://github.com/algolia/docsearch-configs/pull/130 as well). 
The other languages can only be added as soon as this is merged.
> feat(documentation): i18n on the docsearch

- lang/en/docs/_ci/circle.md
Our Yarn doc moved. It's redirected but a direct link is better.
> Fix CircleCI doc link.

- lang/en/docs/cli/global.md
Numerous people including myself have gotten tripped up on this or are incorrectly writing "yarn add global" in their docs.
https://duckduckgo.com/?q=%22yarn+add+global%22&t=ha&ia=web
Some sort of note, if not this one, might limit this.
> Add note about "yarn global" command order

- js/src/documentation.js
so the syntax changed a little as to what I expected, and this PR is needed to make sure that only the current language is shown in the result.
If the language isn't in the list of languages indexed by algolia ([docsearch-configs](https://github.com/algolia/docsearch-configs/blob/master/configs/yarnpkg.json))
cc @daniel15
> feat(docsearch): only use active language

- js/src/lib/Search/index.js
You don't need to fetch all of the attributes in the search (especially once the readme would be indexed), so this means the search will become slightly faster (not really noticeable to my eye, but it's the thought that counts, since #millisecondsmatter).
This PR is needed before https://github.com/algolia/npm-search/pull/23 can be merged to avoid a slowdown
> feat(search) only retrieve some attributes

- _layouts/default.html
- opensearch.xml
closes #405
All browsers that support the "search in this site" spec use this version.
> feat(search) add opensearch.xml

- _data/guides.yml
- _data/i18n/en.yml
- lang/en/docs/offline-mirror.md
- lang/en/docs/prune-offline-mirror.md
Docs for yarnpkg/yarn#2836. @bestander said we can convert the [blog post](https://yarnpkg.com/blog/2016/11/24/offline-mirror/) later.
> Add some offline mirror docs

- _layouts/default.html
- opensearch.xml
Firefox does not show the ability to add the site as a search provider when there is an xml declaration at the top of the file.
This commit removes it so that the search works with Firefox.
Also add a title to the link, as suggested by the MDN docs
Confirmed to work on localhost:4000
> fix(search): Fix OpenSearch file in Firefox (#405)

- opensearch.xml
because a redirect takes you from /packages?q=whatever to /en/packages, which forgets the querystring, linking to en by default (from which you can then change your language) seems like a good solution.
see also #406 and #405
> fix(opensearch) link to /en/ by default

- _layouts/pages/install-ci.html
- lang/en/docs/_ci/solano
Add documentation around using yarn with SolanoCI to the CI page
So that people are aware of Solano and their native support of yarn
> feat(documentation) add solano to ci docs

- _includes/docsearch.html
- _sass/_search.scss
1. layout for the searchbox to take up all the space on layouts smaller than `-lg`
2. apply custom docsearch style again
- this was enabled in the December version, but overriden by docsearch. Now the selector issues have been fixed and the colours have been made in such a way that they apply correctly. 
before|after
---|---
> fix(docsearch): custom styling

- _data/i18n/en.yml
- _includes/i18n-as-script.html
Because in some places operations like `.replace()` are used on the strings, and this doesn't work on `null`, languages that weren’t fully translated gave errors.
What’s done is to give them a default value of the English version of the text (which is a better experience anyway). 
Meanwhile I separated the values used in script from those not used in script.
(to be checked in the deploy preview, since i18n is very hard to test locally) [link](http://deploy-preview-429--yarnpkg.netlify.com/en/)
fixes #427
> fix(i18n): provide a default value for scripted langs

- _includes/i18n-as-script.html
there is broken comment showing up in index page.
it can be written in js comment `//` or liquid comment `{% comment %} {% endcomment %}`. but I thought it was originally written in liquid so I fixed it like it :)
> fix broken liquid comment

- _redirects
For some reason, Netlify interprets /en/packages/ to match /:lang/package/*, so this here will override that behaviour
(waiting on the deploy preview to see if it does the job)
> fix(redirects): explicitly route /packages/ to /packages/

- js/src/lib/Search/index.js
One of the higher ranked searches that return no results is `creatreactnative`. Once this is merged it will match `create-react-native` etc, since the relevancy for words with special characters in it is higher. Obviously the exact name will match either first or second depending if it has more downloads.
Because both `react-native` (real one with lots of downloads) and `reactnative` exist, in this case the one with the most downloads and the same concatenated name will show up first, the one with less downloads second.
You will see the changes already live for `createreactnative`, since they are purely Algolia side, but this PR is visible with the query:
before|after
---|---
https://yarnpkg.com/en/packages?q=reactnative | https://deploy-preview-441--yarnpkg.netlify.com/en/packages?q=react …
> feat(search): more relevancy when name is concatenated

- js/src/lib/Search/index.js
This PR adds a new feature - the `<SearchBox />` component now has the `autoFocus` property when the user loads the search page. 
When I arrive at the search page from an OpenSearch search in my browser, I would like to easily continue my search experience. Say I had a typo in my search, I would like to be able to correct it. Today I have to use my mouse to click the search field, then correct it and press enter. The mouse part seems redundant, so that is what this PR addresses.
See also https://github.com/yarnpkg/website/issues/405
> feat(search) autoFocus SearchBox on search page

- _includes/version.html
- _layouts/page.html
- _layouts/pages/homepage.html
- _layouts/pages/install.html
closes #252
It's now possible to add any `hero_subtext` include by listing the _includes filename in the frontmatter of a layout or a page.
see http://deploy-preview-444--yarnpkg.netlify.com/en/docs/install/
> docs(install): list the version on the installation page

- _data/i18n/en.yml
- js/src/lib/Search/Results.js
We're seeing some queries that are actually meant for the documentation, like `--pure-lockfile`. To guide those people towards the documentation, a phrase is added to the bottom that links to the documentation.
To add the link to wherever it needs to be, depending on the language, another solution than the previous `.replace` had to be taken (splitting, replacing by a React element, mapping).
In the future the results of docsearch might be added in this search might be done, but that's a lot more work than this.
before|after
---|---
> feat(Search): link to documentation in no results

- lang/en/docs/_installations/linux.md
Update from the tool-dependent command to the standard installation step
The package is available in the official repositories since this commit:
https://git.archlinux.org/svntogit/community.git/commit/?id=1b135175a47e20d9c9fb7ccd0baec205178a9889
> docs(install): update Arch Linux section

- js/src/lib/Details/Activity.js
before: using `.reverse()` on an array that was used in other places too
It showed the most recent, but since that modifies the array 😠  it broke the other usages, namely the graph
after: `weeksSinceLastCommit` uses `.slice()` to make a copy of the array to do its calculation on, and consistenly shows the same (correct) data
https://deploy-preview-464--yarnpkg.netlify.com/en/package/react
> fix(Activity): bug in commit activity

- lang/en/docs/cli/unlink.md
- lang/en/docs/installing-dependencies.md
Stumbled upon the following two pages in the docs which contain a couple of relative/broken links when the pages are requested with a trailing slash. I have fixed these links to become absolute ones in order to be consistent with the rest of the pages.
- https://yarnpkg.com/en/docs/cli/unlink/
- https://yarnpkg.com/en/docs/installing-dependencies/
This problem is not noticeable when browsing normally on the Yarn website, because the whole navigation is working (and linked) without trailing slashes, although the `canonical` tags and therefore indexed pages always contain the trailing slash.
The localized canonicals are also a bit inconsistent. While the English docs landing page for example is reachable via `/en/docs/` _(with or without trailing slash)_, its canonical is pointing to …
> Fix relative/broken links in docs

- Makefile
- _layouts/default.html
- package.json
- scripts/sitemaps.js
- yarn.lock
This will only be enabled on production deploys, but for now on this first preview too, to check if it works.
It basically browses through all Algolia records and then makes a record for each language in a sitemap.
This will after the merge be needed to be linked to Google Webmaster Tools.
see https://deploy-preview-468--yarnpkg.netlify.com/sitemaps/sitemap-index.xml for the sitemap index and https://deploy-preview-468--yarnpkg.netlify.com/sitemaps/sitemap.0.xml for an example
> feat(SEO): add a script to make sitemaps

- _sass/_search.scss
- js/src/lib/Search/Results.js
- js/src/lib/Search/withUrlSync.js
1. Use infinite hits instead of pagination
- the actual page number doesn't really matter much
- move the page number out of the URL
- UX for landing on a page is weird
- we didn't use that parameter in showing the results
2. Show number of results
- more useful than the pagination, since it's a number
- also shows the ms it takes to do this request 
https://deploy-preview-478--yarnpkg.netlify.com/en/
> Improve the Search results

- lang/en/docs/cli/why.md
This style of markup for command examples was copied from `version.md`.
The current rendered version: https://yarnpkg.com/en/docs/cli/why
> Fix syntax highlighting of example output for `yarn why`

- lang/en/docs/_ci/travis.md
The previous section of the page, "sudo-enabled builds", recommends locking the version of yarn when installing for ci. (See the deb-specific-version.md include)
No similar example is given for `container-based builds` so this simply updates that example.
> add version flag to travis container-based builds

- js/src/lib/Hit/index.js
- js/src/lib/Search/Results.js
- js/src/lib/Search/SearchBox.js
- js/src/lib/Search/index.js
- js/src/lib/util.js
- package.json
- yarn.lock
React InstantSearch now publishes es2015 modules, and thus the advantage for writing the content of the respective files isn't really there anymore. This makes the code simpler, as well as a few kb's smaller 🚀
> Use treeshook version of react-instantsearch

- lang/en/docs/_installations/unix_path_setup.md
``export PATH="$PATH:`yarn global bin`"`` doesn't work or make sense as a step right after installing/extracting yarn. I'm adding this as an equivalent to the Windows instructions underneath: 
Feel free to correct/update the wording of the update!
> Add instructions to add Yarn to path on Unix/Linux/macOS

- js/src/lib/Details/index.js
- js/src/lib/Search/index.js
- js/src/packages.js
vendor.js:
size | before|after
---|---|---
Encoded | 183.54 KB |181.00 KB
Decoded	|753.04 KB| 736.93 KB
Transferred |183.94 KB| 181.32 KB
> feat(size): use algoliasearch/lite

- js/src/lib/Details/index.js
Google will pick up on this because it loads JavaScript 🙌, FB, Twitter and others will as well, because they're being marked as bots and thus need to be prerendered by Netlify.
At some point I also want to give each package an image that's being generated with data, but that's a different question
> feat(meta): set <head> meta data when data loads

- js/src/lib/Details/Activity.js
- js/src/lib/Details/Copyable.js
- js/src/lib/Details/Header.js
- js/src/lib/Details/Links.js
- js/src/lib/Details/ReadMore.js
- js/src/lib/Hit/index.js
- js/src/lib/Search/withUrlSync.js
- js/src/lib/deeplink.js
- js/src/nightly.js
- js/src/package.js
- package.json
- yarn.lock
1. some dependencies without any significant change
2. algolia-sitemap now generates less sitemaps because they are aggregated to 50k links per sitemap (the maximum)
3. react to 15.5.4 -> all dependencies are compatible without warnings
4. prettier -> run it on all files again, so the js diff is only because of that.
> chore(deps): update all js dependencies 2017-05-12

- _sass/_details.scss
- css/main.scss
- js/src/lib/Details/Activity.js
- js/src/lib/Details/FileBrowser.js
- js/src/lib/Details/Popularity.js
- js/src/lib/Details/Usage.js
- js/src/lib/Details/Versions.js
- lang/en/package.html
- package.json
- yarn.lock
For this to make sense I added a background on hovering a certain listing, since they might sometimes be pretty wide.
I also added another utility class that should be in bootstrap, but isn't for some reason, but it's to align on the baseline.
I used the small [bytes](https://yarnpkg.com/en/package/bytes) utility to show the sizes in kB etc.
Screenshot:
[preview](https://deploy-preview-494--yarnpkg.netlify.com/en/package/algoliasearch-helper)
> feat(files): show size in file listing

- lang/en/docs/usage.md
Adding reference examples of adding a dependency to different categories of dependencies as outlined in the MAN pages of Yarn
> Adding example of cli flag for dependency categories

- _data/guides.yml
- _data/i18n/en.yml
- _redirects
- lang/en/docs/cli/global.md
- lang/en/docs/cli/list.md
- #356 did not create redirect
- #334 duplicated some work already done in #333 also did not update
all necessary files.
Once this is merged, but #334 and #356 can be closed.
> Finish the rename of `yarn ls` to `yarn list`.

- lang/en/docs/cli/cache.md
`YARN_CACHE_FOLDER` environment variable and all other CLI flags will also read from the environment by default.
> Add reference to `YARN_CACHE_FOLDER`

- lang/en/docs/cli/install.md
There was no doc for yarnpkg/yarn#2223.
Note: I don't know about the significance of `NODE_ENV` and if it's used to decided anything other than installing `devDependencies` or not. This PR only speaks of `devDependencies` (as was the case before it).
> Added missing doc: production=false overrides NODE_ENV

- lang/en/docs/_installations/alternatives.md
A version of this was originally submitted in https://github.com/yarnpkg/website/pull/484 and closed in favor of https://github.com/yarnpkg/website/issues/485 which got merged.
I think we can further improve it to make it clear this is not a dig at npm, and that the problem is common to any mainstream Node-based package managers. I kept the title as `Install via npm` and kept the mention of npm in the first sentence because that's realistically what people are going to do, but I hope this makes it clearer that the issue is not in npm itself, but rather that today’s Node package managers don’t give these guarantees (Yarn being no exception).
> Reword npm installation warning to avoid wrong implications

- js/src/lib/Hit/index.js
The `deprecated` value in the index is either `false` or a string. This adds that string as a `title` to that badge. In the future this message would be visible more clearly, but I couldn't think of a good UI to put it, so this is a nice inbetween state where you can already read the message if you want
related: https://github.com/algolia/yarnpkg-website/issues/20#issuecomment-304726188
cc @vvo
> feat(deprecation): show deprecated message

- js/src/lib/Details/Header.js
- js/src/lib/Hit/index.js
On the search page the deprecation message will show instead of the description
On the detail page the deprecation message is visible in bold before the description
cc @vvo
before|after
---|---
> feat(deprecation): make more visible

- _data/i18n/en.yml
- js/src/lib/Search/Results.js
before|after
---|---
the number will use the locale of the current url, as in other places
> feat(i18n): add translation key for stats

- lang/en/docs/_installations/mac.md
Fixes https://github.com/yarnpkg/yarn/issues/3255
> Add homebrew install instructions for nvm compat

- _data/i18n/en.yml
- _layouts/pages/docs.html
Allows to translate "Read more" in Crowdin for the page that is [here](https://yarnpkg.com/fr/docs) :
> feat(i18n): add translation key for "Read more"

- lang/en/docs/cli/upgrade.md
This is the documentation change that corresponds to https://github.com/yarnpkg/yarn/pull/3510
They should be merged at the same time.
> Upgrade docs to add `yarn upgrade --latest` flag

- _posts/2017-05-19-supporting-more-registries.md
As discussed with @bestander in https://github.com/yarnpkg/yarn/pull/3231, I added a quick post explaining the new feature.
I don't really know what the guidelines are for the posts on your blog so I tried to align myself to some of the previous ones. Feel free to criticize or change anything as it makes sense to you 👍
> Add post announcing new custom-host-suffix option

- js/src/lib/Details/Markdown.js
Raw html doesn't get lexed and parsed by Marked, and thus the custom rules for images and links don't get applied. To fix that, the same rewriting needs to happen on raw html too.
I might have a little duplicate code here, I wonder how to make it simpler, but I'm pretty tired now and this works at least.
closes prettier/prettier#2186
closes #531
note: might want to switch to something that works nicer with React than marked, and has the same rewriting and GFM capabilities, but not worth the effort yet
> fix(markdown): rewrite urls to GitHub relative ones in raw html

- lang/en/docs/yarnrc.md
Updated the docs for child concurrency attribute of .yarnrc file 
Reference: [yarn#3632](https://github.com/yarnpkg/yarn/issues/3632)
> Updating child concurrency config in yarnrc

- _sass/_heros.scss
- js/src/common.js
- js/src/lib/serviceStatus.js
I set up a status page at https://status.yarnpkg.com/ as suggested in #416. When the status is "bad" (ie. something is broken), we should show a banner on the site:
Closes #534
> Show system status message on website when available

- lang/en/docs/cli/upgrade-interactive.md
Incorrect help option was being used [here](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/upgrade-interactive.js#L17). The default mode uses minor versions, and tilde should refer to patch (separate PR for help option here: https://github.com/yarnpkg/yarn/pull/3690)
> Update upgrade-interactive to use correct semver

- _layouts/default.html
- lang/en/docs/index.md
The only page where docsearch (currently) is visible is on /lang/docs/, not any other page. So in the time that it isn't visible in other places, it should only be included there
<https://fix-docsearch-style-when-needed--yarnpkg.netlify.com/en/docs> with the css
<https://fix-docsearch-style-when-needed--yarnpkg.netlify.com/> without the css 
This is a 10kb (pre-gzip) win on pages that aren’t /en/docs
> fix(css): only include docsearch style on needed page

- .babelrc
- package.json
- yarn.lock
* transform-react-constant-elements for extracting constant JSX
* transform-react-inline-elements for inlining JSX as a React object
I added these as a test, you can see the result at <https://feat-react-babel-transforms--yarnpkg.netlify.com/en/>
I didn’t see a significant improvement with this though, so I’m not sure if it’s really needed here.
> feat(build): use babel react transforms

- _data/i18n/en.yml
- css/main.scss
- js/src/lib/Details/Copyable.js
- js/src/lib/Details/index.js
Inspired by the package 404 page of npm, maybe some more changes are needed, I don't really want to infringe or anything
example of a 404
https://feat-404-package--yarnpkg.netlify.com/en/package/absurd-package-name
regular page: 
https://feat-404-package--yarnpkg.netlify.com/en/package/react
> feat(Detail): give a special page when the package doesn't exist

- lang/en/docs/cli/version.md
According to the [code](https://github.com/yarnpkg/yarn/blob/v0.27.0/src/cli/commands/version.js#L145) the option is `version-sign-git-tag` not `version-git-sign`.
Fixes https://github.com/yarnpkg/yarn/issues/3177
> Fix the signing git tags config option

- js/src/lib/production.js
The blog page doesn't have a language dropdown, so this event listener adding does not make sense.
fixes #546 
You can check this by seeing if there are console errors on the blog page comparing [this preview](https://deploy-preview-551--yarnpkg.netlify.com/blog) with the [live version](https://yarnpkg.com/blog)
> fix(blog): don't check for language dropdown if not i18n

- lang/en/docs/_installations/linux.md
This is quite a common gotcha for people trying to install `yarn` on Ubuntu 17.04. Would be nice if it was included in the documentation to provide an early heads up.
Refer to [this](https://github.com/yarnpkg/yarn/issues/2821) for more details.
> Add note about cmdtest in Linux installation docs

- lang/en/docs/_installations/tarball.md
Add the GPG verification commands in the manual installation instructions so that people are more likely to actually do it when manually installing Yarn.
> Add GPG verification commands to tarball instructions

- lang/en/docs/_installations/nightly.md
Easiest way was not the easiest way. It's now changed to a oneliner to make it easier and consistent with *install a specific version* document.
Ref: https://github.com/yarnpkg/website/blob/master/lang/en/docs/_installations/tarball.md#installation-script
> Make nightly installer oneliner consistent with other installation docs

- lang/en/org/release-process.md
Updates the release documentation to reflect the current state of things. 
- Updated most of the text to be less verbose
- Added instructions for promoting RC to stable
- Added sections for debugging common issues. This is currently small but we can add more stuff as needed
- Removed the overly-verbose description of the old manual process
- Manual steps for end-to-end release process are all documented, for a better understanding of exactly what happens on AppVeyor, CircleCI, and our release scripts
cc @bestander @byk @arcanis
> Rewrite release docs

- _sass/_search.scss
- js/src/lib/Hit/index.js
- js/src/lib/Search/Results.js
- js/src/lib/Search/index.js
- js/src/lib/util.js
Hey, 
So what happens here, is that we add a refinementList which renders nothing, but is used for its logic alone. When someone clicks on a keyword, it gets refined and shown in `currentRefinements`, and when a refinement is removed from there or another widget, it gets unrefined too.
This was an experimentation to see if this pattern was possible (so for that, yes it works @mthuret, @kikobeats)
> feat(Search): allow to click on a keyword to refine it

- js/src/lib/Details/Links.js
- lang/en/package.html
I saw a link to https://hex.pm/ somewhere which made me discover that there's a `.pm` TLD. Nice! pm = package manager. 😛 
I picked up the `yarn.pm` domain and made it do the same thing as `yarn.fyi`.
> Replace yarn.fyi with yarn.pm

- .babelrc
- package.json
- yarn.lock
More info: 
- http://babeljs.io/docs/plugins/preset-env/#how-it-works
- https://github.com/babel/babel-preset-env
- Added `babel-preset-env`
- Removed `babel-preset-es2015`
> Babel-preset-env

- js/src/lib/Details/index.js
This happens for example in [yarn.pm/react-condition](https://yarn.pm/react-condition)
`(false >= 0) === true`, which makes stuff more complicated, which is why I just gave it 0.
fixes #621
> fix(stargazers): put 0 stargazers if a GitHub repo is available but 404s

- install.sh
**Summary**
Alpine Linux comes with BusyBox tar, which lacks the `--strip` option. This patch updates the `install.sh` script to not rely on this option.
Resolves https://github.com/yarnpkg/yarn/issues/4280.
**Test plan**
Manually verified on local Ubuntu for Windows.
> Fix: Make install.sh Alpine linux compatible

- install.sh
Documented in: https://github.com/yarnpkg/website/issues/647
basically older versions of OSX require a template always to be passed to `mktemp`
> Fix: make install.sh compatible with pre-Sierra OSX (#647)

- _config.yml
- _data/i18n/en.yml
- _includes/version-and-compatibility.html
- _layouts/pages/install.html
You can change which versions of node we support in _config.yml#node_support
I put it visible on /en/docs/install
looks like: 
fixes #646
> fix(install): show node support

- lang/en/docs/_installations/linux.md
Comment about Ubuntu 16.04 is no longer valid. Seems the nodesource repo is now needed for 16.04 too. (unless I have something really crazy going on in my system - but it's a pretty vanilla 16.04 server)
> Corrected compatibility comment relating to Ubuntu 16.04

- lang/en/docs/cli/cache.md
- lang/en/docs/cli/licenses.md
- lang/en/docs/cli/owner.md
- lang/en/docs/cli/tag.md
- lang/en/docs/cli/team.md
These are all the places I could find with `ls`. This should be okay without any special changes to Crowdin or whatever, since no files changed.
fixes #660
> fix(list): rename ls to list in subcommands

- lang/en/docs/cli/global.md
I was going through old emails and saw #554. Noticed that this page says "binaries", but npm packages very very rarely contain binaries. I think this should actually say executables (which includes scripts) and not binaries (which usually refers to compiled code)
> Change "binaries" to "executables" in global.md

- lang/en/docs/cli/index.md
Helping new users who handle an existing (e.g. 3rd party) package.json realize that 'yarn <unlisted-command>' runs a custom script.
> Clarified that 'yarn <unlisted-command>' runs a custom script.

- lang/en/docs/cli/autoclean.md
I believe the following line makes more sense as to how `.yarnclean` works:
> After an `add`
vs what's currently written:
> After as `add`
> Fix grammar error in `autoclean.md`

- _config.yml
**Summary**
Makes the advertised supported Node versions in line with the one in Yarn code:
https://github.com/yarnpkg/yarn/blob/f5e78ebb9dd9809c00a0bdff37d75f324fb42018/src/constants.js#L14
**Test plan**
N/A
> fix(docs): Update supported node versions

- _sass/_readmore.scss
On a package pages with links in the readme (such as https://yarnpkg.com/en/package/ldap-promise), there are links visible but they are not clickable, even though the text is selectable with a mouse.  This CSS change prevents the pointer from interacting with the read more overlay, meaning the browser can interact with links and other UI elements.
The previous workaround was to open the read more section, but this is non-intuitive.
> Allow link interaction in Read More sections

- lang/en/docs/cli/outdated.md
Hey :wave:
I noticed that the CLI output of `yarn outdated` doesn't seem to be up-to-date, so I added the additional `Package Type` and `URL` information.
> Updates CLI output of `yarn outdated`

- js/src/lib/Details/Markdown.js
GitHub will return the wrong content-type and it will result in a broken image. This fix is only added in situations where String has `endsWith`, but that's okay since it's a very niche usecase
check: `@code-therapy/packages-with-readme-relative-images`
fixes #692 
cc @smotaal
> fix(details): manually sanitize relative svgs

- js/src/lib/Search/SearchBox.js
Because the referential equality of these two functions is different, it caused the SearchBox to rerender, and thus send a new query.
> fix(search): don't cause rerenders of SearchBox component

- js/src/lib/Details/index.js
An example for this one is `duivvv` which has the "no readme data" from npm, then we fallback to GitHub, but the repo doesn't exist. It then throws an error because the readme is now `undefined`, which has no `length`. So we add a default to readme of an empty string
> fix(details): handle case where GitHub link 404s

- lang/en/docs/cli/global.md
I didn't add this as a `yarn dir` command link, because it doesn't exist
ref: https://github.com/yarnpkg/yarn/pull/4522 and https://github.com/yarnpkg/yarn/issues/2652
> add yarn global dir

- lang/en/org/contributing.md
As @Daniel15 suggested in https://github.com/yarnpkg/yarn/pull/4803#issuecomment-340511925, contributing page on the website should also be up-to-date with the changes, so I've combined changes from https://github.com/yarnpkg/yarn/pull/4803 and https://github.com/yarnpkg/yarn/pull/4386.
It's kind of tedious to make all these changes twice, so we should think about some way of linking this page with the `CONTRIBUTING.md` from the main repo, see: https://github.com/yarnpkg/yarn/pull/4386#issuecomment-328365590. I can try to work on that if you want. Has any dependency/cross-link to `yarn` already been set up in this repo?
> docs(contributing): Update with sections from `yarn` CONTRIBUTING.md

- lang/en/docs/cli/autoclean.md
Fixes https://github.com/yarnpkg/yarn/issues/4879
Clarify/stress that the default entries created by `yarn autoclean --init` are a reasonable guideline, but should be reviewed and modified to fit actual needs.
> Clarify autoclean default entries. Encourage review and modification.

- lang/en/docs/cli/autoclean.md
Fix typo word "comamnd" to "command"
> Docs: Fix typo in autoclean.md

- lang/en/docs/yarnrc.md
As per line 70, there needs to be a dot between the command and the flag.
> Missing dot

- lang/en/docs/migrating-from-npm.md
The npm/Yarn comparison has been revised to reflect the latest version of npm.
Alternative commands have also been removed (`yarn add [package] [--dev/-D]` is now `yarn add [package] --dev`) to reduce noise. Both CLIs have many aliases/shorthands and listing them all in the comparison table would be pretty complex.
I hope this way, the table better serves as a top-level comparison.
> Update npm usage to match the latest version

- js/src/lib/Details/FileBrowser.js
Replaces usage of unpkg.com API with jsDelivr API for the file browser as previously discussed, because it is more stable and built for production usage. The API is also versioned which means there are never breaking changes such as #614.
> Replace unpkg.com API with jsDelivr API in file browser

- _posts/2017-07-26-introducing-workspaces.md
On the live Yarn website, the flag is rendered as –use-workspaces (notice the n-dash instead of `--` prefixing the CLI option).
This is probably due to some automatic typographical improvements that are applied at build time. I've wrapped the option in `code`, which should hopefully fix this.
> Fix minor issue referencing Lerna CLI flag

- _sass/_details.scss
Adds some CSS to make this look better: https://yarnpkg.com/en/package/ractive-component-loader
> Fix CDN links for packages with long names

- install.sh
I prefer using install.sh script for managing Yarn on my Raspberry Pi.
This seems to work both for Mac and a Raspbian OS.
@Daniel15, does it look reasonable?
> added global bin folder to PATH

- _posts/2017-07-26-introducing-workspaces.md
If you don't do it, you'll end up with an obscure error about missing `lerna.json`.
https://github.com/lerna/lerna/issues/1067#issuecomment-357023774
> Add "lerna" key to the example lerna.json

- js/src/lib/Hit/index.js
This was breaking the whole app, since we were calling `.toLocaleString()` on `undefined`, which errors.
fixes #756
cc @ajaymathur
> fix(search): give a default in case `downloadsLast30Days` is not given

- _posts/2017-07-26-introducing-workspaces.md
Currently the markdown list doesn't indent the content of the code 4 spaces which causes markdown to treat each item as a new list and show `1.` for each one (Markdown doesn't care what number you give to list items). This PR uses the correct indentation and also uses `1.` for each list item which is markdown convention.
Before:
After:
> keep markdown 1. ordering with code blocks

- lang/en/docs/_installations/linux.md
This PR is to document `yarn` installation process in `Ubuntu` when using `nvm`, avoiding `node` installation and setup to use `nvm` version. Based on https://github.com/yarnpkg/website/issues/762.
> doc/ubuntu nvm: Ubuntu NVM howto

- js/src/lib/util.js
The problem is that markdown will interpret a single space as identical to "nothing", whic it isn't.
So as a fix, in the code for safe highlighting of markdown, I wrote `xss(...) || ' '`, which will make sure that if nothing is returned by the markdown parser, I return a space. Technically it's possible now that in the case of a completely empty description, a single space is shown instead, but practically that can't happen, since npm will pick the beginning of the readme if the description is empty.
|before|after|
|---|---|
|<img width="598" alt="screen shot 2018-02-13 at 11 00 48" src="https://user-images.githubusercontent.com/6270048/36144066-2e7e0b6e-10ad-11e8-936d-0e00142a9f85.png">|<img width="593" alt="screen shot 2018-02-13 at 10 57 09" …
> fix(highlighting): make sure spaces in description highlight render as spaces

- lang/en/docs/cli/index.md
- lang/en/docs/cli/install.md
Was searching for an option to print all of the info when running `yarn install` and found the exact option in an issue [#763](https://github.com/yarnpkg/yarn/issues/763) instead of having it in the docs, therefore I am adding it to the docs for future wanderers like me.
> Add docs for `yarn install --verbose`

- lang/en/docs/_installations/linux.md
The default install doesn't come with wget, but it does come with cURL. So this command has a better chance of working without requiring installing another dependency.
> Use curl instead of wget on CentOS / Fedora / RHEL

- _config.yml
Needed to show that Yarn supports the 9.X Node release
> Update the supported node versions

- _includes/footer.html
The webpage link to [shittywatercolour.com](shittywatercolour.com) for Shitty Watercolour's Artwork gives a 404 error. This pull request replaces the link with his [Wikipedia Page - Hector_Janse_van_Rensburg](https://en.wikipedia.org/wiki/Hector_Janse_van_Rensburg) to show credit and match his website link on [Twitter - @SWatercolour](https://twitter.com/SWatercolour).
> Update Shitty Watercolour Link

- lang/en/docs/_ci/circle.md
Moving the link to CircleCI 2.0 as 1.0 will be sunsetted within 6 months.
> Update CircleCI documentation.

- _data/guides.yml
Hi
At first I was surprised to not find the `list` command in the right sidebar.
Then I realized it was in a stray position.
> fix: reorder cli commands alphabetically

- lang/en/docs/yarn-workflow.md
⛏Changes i.e. (*id est*, that is) to e.g. (*exempli gratia*, for example) as git is only one among many VCS options. As a reference, [the Spanish translation](https://yarnpkg.com/es-ES/docs/yarn-workflow) is using "por ejemplo".
*(BTW, where are the sources for translations?)*
> fix: nit in workflow step

- _posts/2018-04-18-dependencies-done-right.md
This diff adds a new article explaining the difference between the `dependencies` and `peerDependencies` fields. It's something often misunderstood, so I figured having it under the hand might be useful when answering some issues.
> Blog post: Dependencies Done Right

- _redirects
**Summary**
Fixes #385. Adds redirects to English pages for unsupported languages.
**Test plan**
Manual verification.
> fix(redirect): Redirect to English pages for unsupported langs

- lang/en/docs/migrating-from-npm.md
Especially now that yarn@1.7.0 (which ships the functionality) is released, it seems fitting to add version bumping examples to the npm migration docs
> Migration docs for npm semver version bumping

- lang/en/docs/_installations/debian.md
Works correctly edited to proper: alias node=nodejs
> Typo in debian node alias command

- lang/en/docs/_installations/centos.md
The current (v6) command seems to not work, and in any case I'd suggest current LTS as the way to go.
> Updating NodeSource command to current LTS (v8)

- lang/en/org/contributing.md
Previously it wasn't clear that:
* yarn needs to be built before running tests (since the integration tests otherwise fail; see also yarnpkg/yarn#6351).
* `yarn watch` can be run even without the first `yarn build`.
* `yarn test` actually runs the linters too.
Also adds a "Setup" section covering prerequisites.
> docs(contributing): Make the build/test steps clearer

- lang/en/docs/cli/bin.md
We add documentation for the new feature added in this commit: https://github.com/yarnpkg/yarn/commit/12d8f7fab0875af1e05a91dd5945e05c5350a6d1
> Document new feature for `yarn bin <executable>`

- lang/en/docs/workspaces.md
As workspaces can be at a location such as `<workspace_root>/packages/some-workspace`, it seems clearer to say they must be 'descendants' of the workspace root instead of 'children'.
> 'children' -> 'descendants' for workspace docs

- lang/en/docs/cli/workspaces.md
I opened yarnpkg/yarn#6244 to add the ability to run a command on all workspace. 
This is the related documentation update.
> Added api doc about workspaces run command

- lang/en/docs/yarnrc.md
Following the discussion here https://github.com/yarnpkg/yarn/pull/6465
@arcanis @Gudahtt
> docs(integrity): document unsafe-disable-integrity-migration

- lang/en/docs/cli/install.md
I was glancing on the yarn docs without much knowledge on the topic and the description of `--focus` sounds like black magic out of context. I think a link to the blog will make it a bit more clear.
> Update install --focus docs: link to blog article

- lang/en/docs/cli/global.md
The install directory is not added to the PATH automatically, so it would be nice to let the users know, they have to change that to be able to use the globally installed packages.
See: https://github.com/yarnpkg/yarn/issues/5353
> How to add the install directory to PATH

- _data/i18n/en.yml
- js/src/lib/Details/Aside.js
- js/src/lib/Details/Popularity.js
- js/src/lib/Details/index.js
- js/src/lib/schema.js
Algolia provides jsDelivr hits in it's API, since the data are already there they only need to be displayed in package details.
> Added jsDelivr hits to package details

- lang/en/docs/cli/install.md
Based on a conversation on this Twitter thread: https://twitter.com/arcanis/status/1063043732356898816
This clarifies the difference between when a bare `yarn install` uses `yarn.lock` and when it *updates* `yarn.lock`
I looked into making a change at https://yarnpkg.com/en/docs/installing-dependencies#toc-installing-dependencies but it seemed like that was too much to add for that introductory page. Linking to the `yarn install` page seemed sufficient for folks to dig into more detail and learn about these scenarios.
> Clarify when yarn.lock is or isn't updated

- lang/en/docs/cli/install.md
`yarn install --no-bin-links` is not documented in the website. This change is to add it.
> Add doc for `--no-bin-links`

- _data/guides.yml
- _data/i18n/en.yml
- lang/en/docs/cli/policies.md
The following PR adds documentation for `yarn policies set-version` (https://github.com/yarnpkg/yarn/commit/158da6c6287cbc4fee900e3704f140c3391dc28d)
> Adds documentation for yarn policies

- _posts/2017-07-26-introducing-workspaces.md
In past days, the 'packages' directory has existed only '7.0' branch, not in master.
However, monorepos architecture was landed in master since v7.0.0 release.
Then '7.0' branch seemed to be removed.
So, https://github.com/babel/babel/tree/7.0/packages is not found.
> Fix link to Babel

- lang/en/docs/_installations/mac.md
Homebrew/homebrew-core#36222 removed support for passing arguments to `brew install yarn`. As such, we can no longer specify the `--without-node` option.
> Remove outdated reference to --without-node argument

- lang/en/docs/workspaces.md
Is that supposed to say "npm" instead of "GitHub"? In the second example, I don't know how yarn would know what to download from GitHub in the case of differing versions. If I'm just missing something and "GitHub" is correct, then I'm happy to add some clarifying comments to this PR to help readers understand how yarn can know what to download from GitHub.
> GitHub -> npm

- lang/en/docs/_ci/semaphore.md
Adding `--update-new` ensures that the Semaphore build updates the package lists before attempting to install Yarn. Otherwise it may fail to install if the package list doesn't contain the version you're attempting to install.
> Add --update-new to Semaphore instructions

- lang/en/docs/cli/upgrade.md
Docs for `yarn upgrade` had typo "explicitely" - correct to "explicitly".
> docs: fix typo "explicitly"

- _posts/2017-07-26-introducing-workspaces.md
Some of the steps here are outdated and may not be needed. Hence adding a quote to point to the updated doc on this.
> Pointing to the updated doc on workspace

- lang/en/docs/cli/policies.md
“[checkin](https://en.wiktionary.org/wiki/checkin)” is a noun whereas “[check in](https://en.wiktionary.org/wiki/check_in)” is a verb.
> Fix grammatical error

- lang/en/docs/cli/policies.md
`^1.12.0` matches the latest _minor_ release instead of the latest _patch_ release. For example, it currently matches `1.15.2`.
> Fix logical mistake

- _data/i18n/en.yml
- _layouts/pages/install-ci.html
- _layouts/pages/install.html
- _plugins/file_exists.rb
- lang/en/docs/_installations/gentoo.md
Yarn is available on Gentoo's portage package manager (1), and I
have a pending patch to yarn to provide correct install instructions
from within the yarn cli (2).
(1) https://packages.gentoo.org/packages/sys-apps/yarn
(2) https://github.com/yarnpkg/yarn/pull/7123
> Add Gentoo Linux install instructions

- lang/en/docs/_installations/mac.md
Resolves #941
The `--ignore-dependencies` option is meant for Homebrew developers, and is not supported.
> Remove reference to Homebrew --ignore-dependencies option

- lang/en/docs/package-json.md
I notice that `prepare` was certain script names. 
https://github.com/yarnpkg/yarn/blob/8a671f10c86b66baa74ef6f4cd24d4ca8ee5067a/src/cli/commands/install.js#L1200
> add prepare on certain script names.

- lang/en/docs/cli/install.md
`yarn install --link-duplicates` is not documented in the website.
This PR adds documentation for `install --link-duplicates`. The description is copied from https://github.com/yarnpkg/yarn/blob/bba4dce9018e4fa4ee38b78a5270e72187740d8b/src/cli/index.js#L94.
> Add doc for `install --link-duplicates`.

- lang/en/docs/_installations/tarball.md
Right now the `tar` snippet will fail as the filename is wrong.
> docs(installations): use correct tar filename

- lang/en/docs/cli/audit.md
Documentation for the change made by https://github.com/yarnpkg/yarn/pull/6819/
Adds specific exit codes to `yarn audit` command.
> Add audit command exit code details for yarnpkg/yarn#6819

- package.json
- yarn.lock
We have a security audit warning on `js-yaml` which is indirectly
included by `lint-staged`. Upgrading `lint-staged` to upgrade this
version. Although this is a semver-major change, the breaking
changes should not be affecting this project. If they do, I'll
resort back to selective resolutions to only upgrade `js-yaml`.
> chore(lint-staged): Upgrade lint-staged to upgrade js-yaml

- lang/en/docs/cli/self-update.md
`yarn install` helpfully says
```
warning Your current version of Yarn is out of date. The latest version is "1.16.0", while you're on "1.15.2".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
```
Yet when looking at the self-update documentation it doesn't actually tell you how to update yarn.
> Adding yarn update info to docs

- lang/en/docs/cli/audit.md
It's not clear that using `--level` on the `yarn audit` command does not affect the exit status of the command.
See https://github.com/yarnpkg/yarn/issues/7260
> Updating docs surrounding the yarn audit level flag

- install.sh
When adding `~/.yarn/bin` to `fish_user_paths` the output message was inaccurate. This also means that "Please open another terminal where the `yarn` command will now be available." is not accurate (it will be available immediately), although I am unsure of the best way to structure the code to alter this output.
> Improve output of install script when using fish

- lang/en/docs/cli/workspaces.md
There is missing `--json` option for `yarn workspaces info` command.
> Add json option to workspaces docs

- lang/en/docs/_ci/gitlab.md
`yarn` is not available after simple installation.
Resolve #985.
> Improve docs about installation for GitLab CI

- lang/en/docs/cli/version.md
This commit adds documentation for the changes implemented on the PR https://github.com/yarnpkg/yarn/pull/7336.
They are already live but there was no documentation for this feature.
> Adds prerelease documentation from version 1.17.0

- _data/languages.yml
This change moves `zh-sg` from under `zh-Hant` to under `zh-Hans`
Rationale: Singapore has switched to using the Simplified variant of the Chinese language since 1969
> Fix Singapore Chinese language code

- lang/en/docs/cli/upgrade.md
Add missing `--scope` parameter in usage summary for `yarn upgrade` for a scope. (Omitting `--scope` results in a no-op.) Also remove the optional trailing forward slash (`/`) after the scope name for consistency as the example clarifies what a scope is.
> Correct upgrade scope in usage summary

- README.md
This adds a [Shields.io](https://shields.io) static deployment badge to README.md.
Note that Netlify now supports [status badges](https://www.netlify.com/docs/continuous-deployment/#status-badges), but those [use a UUID as the identifier](https://www.netlify.com/blog/2019/01/29/sharing-the-love-with-netlify-deployment-badges/#how-to-add-a-deployment-badge), which means that it has to be added by someone with access to the Netlify settings page.
> docs(readme): Add deployment badge

- lang/en/docs/_ci/travis.md
Travis CI no longer offers a container-based infrastructure, which makes virtual machines with `sudo` the only option. See [The Container-Based Build Environment is Fully Deprecated](https://changelog.travis-ci.com/the-container-based-build-environment-is-fully-deprecated-84517).
> Remove outdated Travis CI container setup

- lang/en/docs/_installations/debian.md
- lang/en/docs/_installations/nightly.md
In #968 @Daniel15 mentions `apt-get` should be updated to `apt` instead. I changed this in the debian install and nightly install instructions. 
The CI install docs for travis still have `apt-get` (see https://yarnpkg.com/lang/en/docs/install-ci/) I can also change those, but I believe `apt-get` is still preferred in scripts?
> change apt-get to apt in debian installation

- install.sh
After installing yarn, the install.sh script updates the PATH variable in the user's shell profile. Before updating, it checks whether the profile already contains the PATH declaration to skip adding it redundantly. This check is done by searching for 'yarn' anywhere in the shell config, which can lead to false positives in some oh-my-zsh configs such as `plugins=(... yarn)`, leaving the installation unlinked.
This PR makes the check stricter by looking for 'yarn/bin', which is less likely to occur in any context different than a PATH declaration.
> Make PATH check stricter in install script

- lang/en/docs/cli/add.md
This PR adds minimal documentation of the `link:` dependency type. The corresponding RFC is [0000-link-dependency-type](https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-link-dependency-type.md) which has been merged in this PR: https://github.com/yarnpkg/rfcs/pull/34. The original implementation has been merged to yarn two years ago: https://github.com/yarnpkg/yarn/pull/3359.
The comment by @Haroenv on #793 suggested to put the documentation to https://github.com/yarnpkg/website/blob/master/lang/en/docs/package-json.md, but since there's no existing documentation of other dependency types like `file:` on that page, I decided to go the minimal route and just update the documentation of `yarn add` which already has several examples. I can update package-json docs in this or …
> Document `link:` dependency type (#793)

- _includes/version.html
Since the release notes are no longer under the releases, I think it's much more helpful to see the release notes when clicking on the stable version. I'm not sure if it's worth it to add the fragment to the url with the current version since you'd have to change `1.17.3` to `1170` for example - not sure how consistent that's guaranteed to be.
> link to CHANGELOG from stable version link

- _layouts/default.html
`initial-scale=1` unnecessary appears twice in the meta viewport tag. This PR deletes the duplicate.
> Remove duplicate meta viewport property

- lang/en/docs/pnp/getting-started.md
As as a user that is new to PnP but not to yarn who is looking to migrate an existing project, I felt confused about this point when using the getting started docs. I think it would be helpful to add here.
> Add mention to ignore .pnp.* files

- _posts/2017-07-11-lets-dev-a-package-manager.md
- lang/en/docs/yarnrc.md
- lang/en/package.html
:writing_hand: **Fix typos across yarn website repo**
**Files that have typos**
```
website/_posts/2017-07-11-lets-dev-a-package-manager.md:555:17: "becames" is a misspelling of "becomes"
website/lang/en/docs/yarnrc.md:59:43: "parallely" is a misspelling of "parallelly"
website/lang/en/package.html:7:50: "percieve" is a misspelling of "perceive"
```
**PS:** I use [**client9/misspell**](https://github.com/client9/misspell) to scan typos :heart: 
Making the world a better place :innocent:
> Fix typos across yarn website repo

- _posts/2017-07-26-introducing-workspaces.md
Hi there 👋  I noticed a small issue during my documentation travels.
The current URL (`https://lernajs.io/`) pointing to the _*Lerna*_ home page does not work 😢
It looks like the working URL should be changed to (`https://lerna.js.org/`) 🥳
---
---
Thanks!
> Chore: Update Lerna URL lernajs.io => lerna.js.org

- lang/en/docs/cli/upgrade.md
This seems like a typo. I assume it means it will update to the latest version _matching_ the package.json.
> Typo: "patching" -> "matching" in upgrade.md

- lang/en/docs/cli/index.md
Closes #651
This is a copy of an existing PR (#774), moving the documentation added there into the index alongside other global options `--mutex` and `--verbose`.
It's been a while and this feature remains undocumented, which is a shame because it's a very useful one. This has also been discussed in the [issue](#651) and I think this PR provides a good solution.
> Docs: Document the `--cwd` global option

- lang/en/docs/_ci/gitlab.md
This saves caching the whole of `node_modules`, but still provides a performance improvement to builds, as an offline cache can be used.
The default cache location isn't persisted by GitLab
> Explicitly use .yarn directory as cache directory

- lang/en/docs/cli/index.md
Fixes https://github.com/yarnpkg/yarn/issues/5733
By updating documentation :smile:
> Update cli index with note about terminal colors

- _data/i18n/en.yml
- _includes/news.html
- _includes/version-with-upgrade-notice.html
- _includes/version.html
- _layouts/default.html
- _layouts/page.html
- _layouts/pages/homepage.html
- _layouts/pages/install.html
- _sass/_news.scss
- css/main.scss
- js/src/install.js
- lang/en/docs/_installations/alternatives.md
- lang/en/docs/_installations/npm.md
- lang/en/docs/cli/self-update.md
The time for us to add some v2+ upgrade notices has finally come.
This PR adds:
- a migration banner
- a migrate button on the homepage
- updates the installation page to recommend installation via npm
- updates the self-update docs a bit
- adds an update notice to the installation page
- a few other small changes that I've discussed with @arcanis and the rest of the team
> docs: add update notices

- lang/en/docs/cli/run.md
Documenting the hidden `pre` and `post` prefixes that are supported so less people are confused.
I spent an hour of my life trying to figure out why my build got longer and started running tests. I would like it so other developers do not also waste that hour of their life.
> Updating run.md. Documenting the hidden `pre` and `post` prefixes that are supported so less people are confused.

- lang/en/docs/cli/audit.md
It was a bit misleading until now how exactly to use the `--groups` parameter when you want to audit multiple groups at once.  
I added two examples that hopefully clear things up...
see https://github.com/yarnpkg/yarn/issues/8495
> yarn audit: add example how to use multiple groups

- lang/en/docs/cli/link.md
'linking' is something of a symmetric verb. Linking packages A and B doesn't imply a specific hierarchy.
Replacing one instance of *link* here with *consume* make the direction of the dependency more obvious on first read.
> Carify dependency direction in link doc

- _config.yml
- js/src/components/Details.js
See yarnpkg/berry#3425 for motivation. This will update `<link rel="canonical">`, so Google Search will show "classic" URL. Also updates `<meta property="og:url">`.
`_config.yml `: This change will add `classic` subdomain to `<link rel="canonical">` & `<meta property="og:url">` for most pages, via [_layouts/default.html](https://github.com/yarnpkg/website/blob/5be62ee/_layouts/default.html)
`js/src/components/Details.js`: This change will update `<link rel="canonical">` & `<meta property="og:url">` for  "Package detail" pages, e.g. https://classic.yarnpkg.com/en/package/Babel
Note: I haven't yet attempted to test these changes locally. I'm willing to do so if there is any uncertainty as to the outcome. Just took a look at the "deploy preview" and it looks good.
> yarnpkg.com --> classic.yarnpkg.com

- _config.yml
We were falling quite behind in patch releases since the automated pipeline got issues. Updating to the newly released [1.12.13](https://github.com/yarnpkg/yarn/releases/tag/v1.22.13).
> Updates the versions on the website

- _config.yml
It looks like this comment saying to NOT update the yarn version is 5 years old: https://github.com/yarnpkg/website/blame/d0699c5dc13f80f0453d2e2b153b0cf6694320b8/_config.yml
Also, 2nd to last update here: https://github.com/yarnpkg/website/pull/1136
@arcanis suggests that:
> We were falling quite behind in patch releases since the automated pipeline got issues.
Latest version on npm registry is 1.22.17.
1.22.17 has 1.6 million more downloads than 1.22.15: https://www.npmjs.com/package/yarn?activeTab=versions
1.22.17 is merged to 1.22-stable branch: https://github.com/yarnpkg/yarn/tree/1.22-stable
1.22.17 has been released as latest version for longer than 1.22.15.
1.22.17 was released 2 weeks after 1.22.15.
> Promote 1.22.17 on 1.x landing page

- lang/en/docs/cli/add.md
linked issue: https://github.com/yarnpkg/website/issues/1159
`yarn add` documentation page links to https://classic.yarnpkg.com/en/docs/dependency-types#toc-dev-dependencies
while the correct URL is https://classic.yarnpkg.com/en/docs/dependency-types#toc-devdependencies
> Link to correct anchor tag in yarn add documentation page

- lang/en/docs/cli/create.md
In order for `yarn create` to work, the `bin` name in the starter kit’s `package.json` needs to be `create-<starter-kit-package>`: https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/create.js#L71
> fix(create): explicitly indicate the bin name

- lang/en/docs/cli/link.md
We have two project which use yarn, the website uses yarn 1 and the package uses yarn 3.
We want to be able to test & develop package locally and have live updates for the main react app.
I found this pease missing how to support integration with legacy projects.
[related issue](https://github.com/yarnpkg/berry/issues/90)
> Support linking with older yarn versions

- lang/en/docs/creating-a-package.md
This change fixes the missing flag in the first example. If you just run yarn version it will only plot the version, not change it.
Update the note from the end of the first example to the --new-version flag where it is related to.
The current docs say the next about NodeJS:
>   is used to define the entry point of your code used by programs like Node.js. If unspecified it will default to index.js.
This PR proposes to change the NodeJS definition, seeking to avoid confusion about how javascript and javascript packages really work. 
Also,  today NodeJS purpose the "exports" entry point usage instead of "main" entry, and this entry point (exports) has better support for universal packages.
Also is proposed to add a mention of "exports" entry point which is taken over "main" entry point if …
> Add better entry point description

- lang/en/docs/cli/exec.md
Closes #1053
`yarn` implementation has links to this pages (e.g. via https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/cli/commands/index.js#L7), but it seems that this page was never added
> Create missing docs for yarn exec

- _layouts/default.html
Polyfill.io has been compromised and should not be used.
https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/ https://github.com/formatjs/formatjs/issues/4363
https://github.com/sampotts/plyr/issues/2799
https://github.com/remix-run/react-router/issues/11733
> Remove polyfill.io script
